### PR TITLE
New Log-in page

### PR DESCRIPTION
**Pull request by TreeIsLife2**

### CODE REVIEW

**Comment by Markus-Rost** [comment]
This seems to be missing some CSS updates.

**Comment by TreeIsLife2** [comment]
What do you mean with CSS updates?

**Comment by TreeIsLife2** [comment]
You meant i did not put / before src?

**Comment by Markus-Rost** [comment]
The HTML suggests that there was more complex styling planned with boxes for the images and their text.

At the moment it's just plain text between different sizes images not looking very good.

**Comment by Markus-Rost** [comment]
inactive

**Pull request closed without merging**
